show_widget("answer");
show_widget("timer");
set_global_property("totalOperations", random(entity["enemy" + global.property["fighterID"]].property["AttCtMin"], entity["enemy" + global.property["fighterID"]].property["AttCtMax"]));
set_global_property("executedOperations", 1);
set_global_property("correctOperations", 0);
set_global_property("progressTime", global.property["totalOperations"] * entity["enemy" + global.property["fighterID"]].property["opTime"]);
execute_script("progressBar", false);
execute_script("setOperation", false);