$battleNr = 13;
if global.property["fought"] >= $battleNr then
	global.property["battleID"] = "battle_14.json";
	execute_script("battle");
	global.property["preScript"] = "";
	global.property["posScript"] = "";
	global.property["map"] = "forest";
	global.property["x"] = -6;
	global.property["y"] = -23;
	global.property["z"] = 0;
else
	display_message("Pentru a accesa aceasta batalie, va trebui sa termini toate bataliile anterioare!");
end;