$battleNr = 19;
if global.property["fought"] >= $battleNr then
	global.property["battleID"] = "battle_20.json";
	execute_script("battle");
	global.property["preScript"] = "";
	global.property["posScript"] = "";
	global.property["map"] = "snow to desert";
	global.property["x"] = -13;
	global.property["y"] = -35;
	global.property["z"] = 0;
else
	display_message("Pentru a accesa aceasta batalie, va trebui sa termini toate bataliile anterioare!");
end;